import React from 'react';
import { StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  logo: {
    width: 220,
    height: 70,
    fontSize: 20,
    fontWeight: '600',
    textAlign: 'center',
    color: '#68b0ab',
    lineHeight: 35,
  },
  onsiteText: {
    color: 'white',
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: "center"
  },
  consumerWrapper: {
    backgroundColor: '#8FD7D3',
    padding:10,
    width:'100%',
    marginTop:60,
    height:45,
    alignItems: 'center',
    justifyContent: "center",
    borderRadius:25,
  },
  providerWrapper2: {
    backgroundColor: '#196F75',
    padding:10,
    width:280,
    marginTop:30,
    height:45,
    alignItems: 'center',
    borderRadius:25,
  },
  deliveryWrapper:{
    backgroundColor: '#FDB0A8',
    padding:10,
    width:280,
    marginTop:30,
    height:45,
    alignItems: 'center',
    borderRadius:25,
  },
  img2: {
    marginTop:70,
    width:120,
    height:32,
  },
  img: {
    width:375,
    height:375,
  },
  contact: {
    width:220,
    height:30,
    marginLeft:100,
    marginTop:15,
  },
  bottom:{
    marginTop:90,
    marginLeft:50,
  },
  comments: {
    marginLeft:30,
    marginTop:10,
    height:40,
  },
  switch_text: {
    marginTop: 16,
    fontSize: 11,
    color: '#999999',
  },
  switch_container: {
    flexDirection:'row',
  },
  comment_container: {
    flexDirection:'row',
    marginTop:30,
  },
  tick1:{
    marginLeft:40,
    marginTop:10,
  },
  caption2:{
    fontSize:12,
    marginLeft:50,
    marginTop:10,
  },
  caption:{
    fontSize:12,
    marginLeft:50,
    marginTop:10,
  },
  arrow_image:{
    width:25,
    height:25,
    marginTop:20,
    marginLeft:20,
  },
  comment_image:{
    width:25,
    height:25,
    marginTop:20,
    marginLeft:20,
  },
  comment:{
    width:100,
    height:25,
    marginTop:20,
    marginLeft:50,
  },
  service:{
    color:'#006A71',
    fontSize:16,
    marginTop:20,
    marginLeft:160,
  },
  choice:{
    marginTop:20,
    marginLeft:40,
  },
  clean_wrapper:{
    backgroundColor: '#8FD7D3',
    padding:10,
    width:120,
    marginLeft:40,
    marginTop:25,
    height:45,
    alignItems: 'center',
    borderRadius:10,
  },
  next_wrapper:{
    backgroundColor:'#8FD7D3',
    padding:10,
    width:220,
    marginLeft:100,
    marginTop:15,
    height:45,
    alignItems: 'center',
    borderRadius:25,
  },
  care_wrapper:{
    backgroundColor: '#8FD7D3',
    padding:10,
    width:120,
    marginLeft:40,
    marginTop:25,
    height:45,
    alignItems: 'center',
    borderRadius:10,
  },
  onsite_wrapper:{
    backgroundColor: '#8FD7D3',
    padding:10,
    width:120,
    marginLeft:40,
    marginTop:10,
    height:45,
    alignItems: 'center',
    borderRadius:10,
  },
  onsite_text:{
    color: 'white',
  },
  r_text:{
    color: '#333333',
    marginLeft:145,
  },
  f_text: {
    color: '#333333',
    marginLeft:0,
  },
  f_wrapper:{
    marginTop:20,
    marginRight:77,
  },
  z_wrapper:{
    marginTop:20,
    marginLeft:55,
  },
  container2:{
    flexDirection: 'row',
  },
  loginWrapper: {
    backgroundColor: '#8FD7D3',
    padding:10,
    width:'80%',
    marginTop:40,
    height:40,
    alignItems: 'center',
    borderRadius:20,
  },
  img_ac:{
    height:30,
    width:300,
    marginTop:40,
  },
  img_pw:{
    marginTop:30,
    height:30,
    width:300,
  },
  account:{
    height: 35,
    width: '90%',
  },
  password:{
    height: 35,
    width: '90%',
  },
  onsite_text:{
    color: 'white',
  },
  providerWrapper:{
    backgroundColor: '#FDB0A8',
    padding:10,
    width:'100%',
    marginTop:30,
    height:45,
    alignItems: 'center',
    justifyContent: "center",
    borderRadius:25,
  },
  img3:{
    marginTop:70,
    width:300,
    height:300,
  },
  img4:{
    marginTop:90,
    width:120,
    height:32,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  welcomeText:{
    width: 220,
    height: 70,
    justifyContent:'center',
    textAlign: 'center',
  },
  time:{
    marginLeft:40,
    height: 35,
    width: 80,
    borderBottomColor: '#999999',
    borderBottomWidth:1,
  },
  resumeInput: {
    width: 300,
    height: 22,
    marginLeft: 5,
    borderBottomWidth:1,
    borderBottomColor:'#EEEEEE',
  },
});
