import React from 'react';
import { StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  buttonContainer: {
    width: '280px',
    height: '40px',
    alignSelf: 'center',
    marginVertical: 30,
  },
  logo: {
    width: '220px',
    height: '70px',
    fontSize: 20,
    fontWeight: "600",
    textAlign: 'center',
    color: '#68b0ab',
    lineHeight: 35,
  },
  onsiteText: {
    color: 'white',
  },
  container: {
    backgroundColor: 'white',
    marginTop: 20,
    alignItems: 'center',
  },
  consumerWrapper: {
    backgroundColor: '#8FD7D3',
    padding:10,
    width:280,
    marginTop:60,
    height:45,
    alignItems: 'center',
    borderRadius:25,
  },
  providerWrapper: {
    backgroundColor: '#FDB0A8',
    padding:10,
    width:280,
    marginTop:30,
    height:45,
    alignItems: 'center',
    borderRadius:25,
  },
  card: {
    width: 315,
    height: 160,
    marginTop:15,
    marginBottom:15,
    backgroundColor: '#ffffff',
    borderRadius: 15,
  },
  finishImg: {
    width: 300,
    height: 225,
  },
  mainImg:{
    height:120,
    width:120,
  },
  buttons:{
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonContainer:{
    width: 90,
    height: 90,
    marginTop:15,
    marginBottom:15,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: '#9ADAD6',
    borderRadius: 15,
    textAlign: 'center',
  },
  buttonContainer2:{
    width: 90,
    height: 90,
    marginTop:10,
    marginBottom:15,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: '#196F75',
    borderRadius: 15,
    textAlign: 'center',
  },
  smallIconImg:{
    width: 20,
    height: 20,
    marginLeft:10,
    marginRight:10,
  },
  personIcon:{
    width: 78,
    height: 78,
  },
  buttonContainer3:{
    width: 90,
    height: 90,
    marginTop:15,
    marginBottom:15,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: '#FF816B',
    borderRadius: 15,
    textAlign: 'center',
  },
  img2: {
    marginTop:70,
    width:120,
    height:32,
  },
  img: {
    marginTop:30,
    width:380,
    height:500,
  },
  contact: {
    width:220,
    height:30,
    marginLeft:100,
    marginTop:15,
  },
  bottom:{
    marginTop:40,
    marginLeft:50,
    width:380,
    height:50,
  },
  comments: {
    marginLeft:30,
    marginTop:10,
    height:40,
  },
  switch_text: {
    marginTop: 16,
    fontSize: 11,
    color: '#999999',
  },
  switch_container: {
    flexDirection:'row',
  },
  comment_container: {
    flexDirection:'row',
    marginTop:30,
  },
  tick1:{
    marginLeft:40,
    marginTop:10,
  },
  caption2:{
    fontSize:12,
    marginLeft:50,
    marginTop:10,
  },
  caption:{
    fontSize:12,
    marginLeft:50,
    marginTop:10,
  },
  arrow_image:{
    width:25,
    height:25,
    marginTop:20,
    marginLeft:20,
  },
  comment_image:{
    width:25,
    height:25,
    marginTop:20,
    marginLeft:20,
  },
  wechat_image:{
    width:220,
    height:28,
    marginTop:20,
    marginLeft:20,
  },
  name_image:{
    width:80,
    height:30,
    marginTop:20,
    marginLeft:10,
  },
  address_image:{
    width:120,
    height:30,
    marginTop:20,
    marginLeft:20,
  },
  time_image:{
    width:240,
    height:30,
    marginTop:20,
    marginLeft:20,
  },
  comment:{
    width:100,
    height:25,
    marginTop:20,
    marginLeft:50,
  },
  service:{
    color:'#006A71',
    fontSize:16,
    marginTop:20,
    marginLeft:80,
  },
  street:{
    fontSize:18,
    marginTop:20,
    marginLeft:80,
  },
  choice:{
    marginTop:20,
    marginLeft:40,
  },
  clean_wrapper:{
    backgroundColor: '#8FD7D3',
    padding:10,
    width:120,
    marginLeft:40,
    marginTop:25,
    height:45,
    alignItems: 'center',
    borderRadius:10,
  },
  next_wrapper:{
    backgroundColor:'#8FD7D3',
    padding:10,
    width:220,
    marginLeft:100,
    marginTop:10,
    height:45,
    alignItems: 'center',
    borderRadius:25,
  },
  care_wrapper:{
    backgroundColor: '#8FD7D3',
    padding:10,
    width:120,
    marginLeft:40,
    marginTop:25,
    height:45,
    alignItems: 'center',
    borderRadius:10,
  },
  onsite_wrapper:{
    backgroundColor: '#8FD7D3',
    padding:10,
    width:120,
    marginLeft:40,
    marginTop:10,
    height:45,
    alignItems: 'center',
    borderRadius:10,
  },
  onsite_text:{
    color: 'white',
  },
  r_text:{
    color: '#333333',
    marginLeft:145,
  },
  f_text: {
    color: '#333333',
    marginLeft:0,
  },
  f_wrapper:{
    marginTop:20,
  },
  container2:{
    flexDirection: 'row',
  },
  loginWrapper: {
    backgroundColor: '#8FD7D3',
    padding:10,
    width:240,
    marginTop:60,
    height:45,
    alignItems: 'center',
    borderRadius:25,
  },
  img_ac:{
    height:30,
    width:300,
    marginTop:40,
  },
  img_pw:{
    marginTop:30,
    height:30,
    width:300,
  },
  account:{
    height: 35,
    width: 300,
    borderBottomColor: '#999999',
    borderBottomWidth:1,
  },
  topping_image:{
    marginTop:20,
    height:150,
    width:300
  },
  finish_image:{
    marginTop:40,
    height:400,
    width:280,
    marginLeft:40,
  },
  button_image:{
    marginTop:40,
    height:70,
    width:200,
    marginLeft:40,
  },
  time:{
    marginLeft:40,
    height: 35,
    width: 80,
    borderBottomColor: '#999999',
    borderBottomWidth:1,
  },
  street_input:{
    marginLeft:40,
    height: 35,
    width: 300,
    borderBottomColor: '#999999',
    borderBottomWidth:1,
  },
  password:{
    height: 35,
    width: 300,
    borderBottomColor: '#999999',
    borderBottomWidth:1,
  },
  onsite_text:{
    color: 'white',
  },
  consumer_wrapper:{
    backgroundColor: '#8FD7D3',
    padding:10,
    width:280,
    marginTop:60,
    height:45,
    alignItems: 'center',
    borderRadius:25,
  },
  providerWrapper:{
    backgroundColor: '#FDB0A8',
    padding:10,
    width:280,
    marginTop:30,
    height:45,
    alignItems: 'center',
    borderRadius:25,
  },
  img3:{
    width:70,
    height:50,
  },
  img4:{
    marginTop:90,
    width:120,
    height:32,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  home :{
    width:315,
    height:140,
    borderRadius:15,
    backgroundColor:'#FFFFFF',
  },
  card: {
   width: 315,
   height: 160,
   marginTop:15,
   marginBottom:15,
   backgroundColor: '#ffffff',
   borderRadius: 15,
 },
 mainImg:{
   height:120,
   width:120,
 },
 orderImg: {
   width: 375,
   height: 100,
 },
 plans: {
   width: 330,
   height: 120,
 },
 personIcon:{
   width: 78,
   height: 78,
 },
 iconImg:{
   width: 45,
   height: 40,
 },
 smallIconImg:{
   width: 20,
   height: 20,
   marginLeft:10,
   marginRight:10,
 },
 accountBar:{
   flexDirection: 'row',
   justifyContent: 'space-around',
   marginBottom:15,
 },
 profileBar:{
   width: 332,
   height: 25,
   marginTop: 15,
   marginBottom: 15,
   flexDirection: 'row',
   justifyContent: 'space-around',
 },
 benefit: {
   width: 320,
   height: 60,
   marginTop:25,
   marginBottom:30,
   backgroundColor:'#68b0ab',
   borderRadius: 15,
   textAlign: 'center',
   justifyContent: "center",
   alignItems: "center" ,
 },
 orderButton: {
   width: 75,
   height: 30,
   backgroundColor: '#FF7E67',
   borderRadius: 10,
   textAlign: 'center',
   marginRight: 25,
   marginTop: 15,
   justifyContent: "center",
   alignItems: "center" ,
 },
 orderButton2: {
   width: 75,
   height: 30,
   backgroundColor: '#68B0AB',
   borderRadius: 10,
   textAlign: 'center',
   marginRight: 25,
   marginTop: 15,
   justifyContent: "center",
   alignItems: "center" ,
 },
 resumeImg: {
   width:110,
   height:110,
 },
 resumeInput: {
   width: 300,
   height: 22,
 },
 resumeInput1: {
   width: 115,
   height: 22,
 },
 resumeInput2: {
   width: 335,
   height: 22,
 },
 resumeButton: {
   width: 280,
   height: 40,
   marginTop: 40,
   backgroundColor: '#68B0AB',
   borderRadius: 20,
   alignItems: 'center',
   justifyContent: "center",
 },
 resumeSmallButton: {
   width: 60,
   height: 30,
   borderRadius: 10,
 },
 resumeTag: {
   backgroundColor: '#DDDDDD',
   width: 'auto',
   height: 30,
   borderRadius: 10,
   marginTop: 5,
   marginBottom: 5,
   marginLeft: 5,
   marginRight: 5,
   textAlign: 'center',
   paddingLeft:15,
   paddingRight:15,
 },
 resumeTag2: {
   backgroundColor: '#DDDDDD',
   width: 'auto',
   height: 30,
   paddingLeft:15,
   paddingRight:15,
   borderRadius: 10,
   marginTop: 5,
   marginBottom: 5,
   marginLeft: 5,
   marginRight: 5,
   textAlign: 'center',
 },
 bigIconImg: {
   width: 90,
   height: 90,
 },
 commentContainer1: {
   width: 130,
   height: 70,
   marginLeft: 25,
   marginRight: 25,
   justifyContent: "center",
   alignItems: "center",
   backgroundColor:  '#68b0ab',
   borderRadius: 15,
 },
 commentContainer2: {
   width: 130,
   height: 70,
   marginLeft: 25,
   marginRight: 25,
   justifyContent: "center",
   alignItems: "center",
   backgroundColor:  '#FF7E67',
   borderRadius: 15,
 },
 commentIcon: {
   width: 15,
   height: 15,
 },
 commentPerson: {
   width:40,
   height:40,
 },
 commentCard:{
   width: 345,
   height: 100,
 },
 commentTag: {
   width: 'auto',
   height: 30,
   textAlign: 'center',
   borderWidth: 1,
   borderRadius: 10,
   marginLeft:10,
   marginRight:10,
   paddingLeft:10,
   paddingRight:10,
 },
 incomeCard: {
   width:325,
   height: 60,
 },
 incomeIcon: {
   width: 40,
   height: 40,
 },
 finishImg: {
   width: 300,
   height: 225,
 },
 smallAddImg: {
   width: 25,
   height:25,
 },
 pendingImg: {
   width: 40,
   height:40,
 },
});
