export const doctors = [
  {
    name: "李医生",
    language:["中文", "英文"],
    time: {
      "周一": "9:00 - 17:00",
      "周三": "9:00 - 17:00",
      "周五": "9:00 - 17:00",
      "周六": "9:00 - 17:00",
    },
    type: "普通问诊",
    certificate: ["GACCP","SPA"],
    img: require('../../images/providerImg/service_doctor_img1.png'),
    description: '全科医生 - 9年工作经验',
    id: 0,
  },
  {
    name: "王医生",
    language:["中文", "英文"],
    time: {
      "周一": "9:00 - 17:00",
      "周二": "10:00 - 17:00",
      "周五": "9:00 - 17:00",
      "周六": "9:00 - 17:00",
    },
    type: "普通问诊",
    certificate: ["GACCP","SPA"],
    img: require('../../images/providerImg/service_doctor_img2.png'),
    description: '全科医生 - 3年工作经验',
    id: 1,
  },
  {
    name: "陈医生",
    language:["中文", "英文"],
    time: {
      "周一": "9:00 - 17:00",
      "周二": "10:00 - 17:00",
      "周五": "9:00 - 17:00",
      "周六": "9:00 - 17:00",
    },
    type: "心理咨询",
    certificate: ["GACCP","SPA"],
    img: require('../../images/providerImg/service_doctor_img3.png'),
    description: '牙科医生 - 3年工作经验',
    id: 2,
  },
  {
    name: "李医生",
    language:["中文", "英文"],
    time: {
      "周一": "9:00 - 17:00",
      "周二": "10:00 - 17:00",
      "周五": "9:00 - 17:00",
      "周六": "9:00 - 17:00",
    },
    type: "神经理疗",
    certificate: ["GACCP","SPA"],
    img: require('../../images/providerImg/service_doctor_img4.png'),
    description: '心理医生 - 3年工作经验',
    id: 3,
  },
  {
    name: "钟医生",
    language:["中文", "英文"],
    time: {
      "周一": "9:00 - 17:00",
      "周二": "10:00 - 17:00",
      "周五": "9:00 - 17:00",
      "周六": "9:00 - 17:00",
    },
    type: "儿科问诊",
    certificate: ["GACCP","SPA"],
    img: require('../../images/providerImg/service_doctor_img5.png'),
    description: '全科医生 - 3年工作经验',
    id: 4,
  },
  {
    name: "钟医生",
    language:["中文", "英文"],
    time: {
      "周一": "9:00 - 17:00",
      "周二": "10:00 - 17:00",
      "周五": "9:00 - 17:00",
      "周六": "9:00 - 17:00",
    },
    type: "儿科问诊",
    certificate: ["GACCP","SPA"],
    img: require('../../images/providerImg/service_doctor_img5.png'),
    description: '全科医生 - 2年工作经验',
    id: 5,
  },
  {
    name: "钟医生",
    language:["中文", "英文"],
    time: {
      "周一": "9:00 - 17:00",
      "周二": "10:00 - 17:00",
      "周五": "9:00 - 17:00",
      "周六": "9:00 - 17:00",
    },
    type: "儿科问诊",
    certificate: ["GACCP","SPA"],
    img: require('../../images/providerImg/service_doctor_img3.png'),
    description: '全科医生 - 2年工作经验',
    id: 6,
  },
];
