export default {
  orginfo: '个人信息',
  members: '成员管理',
  resetPassword:'修改密码',
  settings:'我的设置',
  logout:'退出登录',
  provider:'开始使用',
  consumer:'我是消费者',
  account:'账号',
  password:'密码',
  forgotPassword:'忘记密码?',
  signup:'注册账户',
  login:'登录',
  name:'姓名',
  mobile:'电话',
  email:'邮箱',
  verifyCode:'验证码',
  confirm:'确认',
}
