export default {
  orginfo: '个人信息',
  members: '成员管理',
  resetPassword:'修改密码',
  settings:'我的设置',
  logout:'退出登录',
  provider:'开始使用',
  consumer:'我是消费者',
  account:'账号',
  password:'密码',
  forgotPassword:'忘记密码?',
  signup:'注册账户',
  login:'登录',
  name:'姓名',
  mobile:'电话',
  email:'邮箱',
  verifyCode:'验证码',
  confirm:'确认',
  loginEmail:'邮箱登陆',
  loginMobile:'手机登录',
  sendCode:'获取验证码',
  resend:'重新获取',
  binding:'绑定方式',
  changePassword:'修改密码',
  mySetting:'我的设置',
  members:'成员管理',
  introduction:'介绍',
  mintro:'成员介绍',
  mlan:'成员语言',
  languages:'语言',
  serviceType:'服务种类',
  stores:'分支机构',
  uploadMember:'成员添加',
  doctorInfo:'成员信息',
}
