
export default {
    types:["推荐医生","全科","牙科","心理","中医","儿科","康复","疫苗"],
    //sign up 
    signup_success:"注册成功!",
    name_up:"姓名",
    name_up_pd:"请输入您的真实姓名",
    mobile_up:"电话",
    password_up:"密码",
    ps_up_pd:"请输入六位数密码",
    confirmation_up:"确认",
    confirmation_up_pd:"请再次输入密码",
    verification:"验证码",
    verification_pd:"请输入验证码",
    send:"发送验证码",
    read:"我已阅读并同意",
    TOS:"用户须知条款。",
    code_send:"验证码已发送。",
    m_pd:"电话号码",
    //forget
    new_password:"新密码",
    new_ps_pd:"请输入六位数字新密码",
    //登陆页面
    phone_signin:"手机号码",
    phone_signin_placeholder:"请输入您的注册手机号码",
    password_signin:"账户密码",
    password_signin_placeholder:"请输入您的密码",
    forget_password_signin:"忘记密码?",
    signup_signin:"注册账户",
    signin:"登陆",
    guest_mode:"游客模式",

    //首页
    myservice_homepage:"热门服务",
    myappointment_homepage:"近期预约",
    aitext_homepage:"使用AI助手来测试心情吧。",
    ordertype_homepage:"您预约了一门",
    no_appointment1:"Hi,您还没有预约哦。",
    no_appointment2:"点击医生预约来进行预约吧:)",
    //tabs
    homepage_tab:"主页",
    service_tab:"双阴检测",
    appointment_tab:"预约",
    account_tab:"账号",

    //服务页
    allservice_service:"所有服务",

    //预约页
    order_order:"订单",
    onsite_order:"实地问诊",
    online_order:"远程问诊 - ",
    cancel_order:"取消",
    change_order:"更改",
    contact_order:"联系",
    notice_order:"仅在预约一小时之前可以进行订单取消或更改。",
    cancelalert_order:"您确定要取消这单预约吗？请注意仅在预约时间一小时之前可以取消预约。",
    confirm_cancel:"确定",
    cancel_success:"订单已取消",
    changealert_order:"您要更改预约时间吗？请注意仅在预约时间一小时之前可以进行更改。",
    confirm_change:"更改时间",
    changealert2_order:"确定要更改时间到",
    changealert3_order:"吗？",
    change_success:"订单已更改",
    no_order:"您还没有预约哦。您可以在首页点击医生预约或者在线就诊进行预约哦:)",
    fail:"请求发送失败。请检查网络连接或者联系客服吧。联系客服可以点击服务页面或者别的页面的电话按钮。",

    //账户页
    personalinfo_account:"个人信息",
    medicare_info_account:"医保信息",
    medical_history_account:"病史信息",
    electronic_prescription_account:"电子处方",
    medication_history_account:"用药历史",
    vaccine_record_account:"疫苗记录",
    cure_history_account:"治愈历史",
    pathology_account:"生化检查",
    contact_us_account:"联系我们",
    logout_account:"退出登录",
    signup_account:"前往注册",
    confirm_logout:"确认",
    language_switch:"语言选择",
    chi:"中文",
    eng:"英文",
    lan_text:"您希望使用哪种语言?",


    //need to add alerts translation here
    //种类页
    title_type:"医生预约",
    category_type:"预约科目",
    recommendation_type:"名医推荐",
    all_type:"全部",
    gp:"全科",
    children:"儿科",
    mental:"心理",
    chinese:"中医",
    recovery:"康复",
    dentist:"牙医",

    //诊所选择
    title_clinic:"诊所选择",
    category_clinic:"科目",
    date_clinic:"日期",
    comments_clinic:"条评论",
    unknown_clinic:"未知",
    waiting_clinic:"正在为您搜索诊所，请稍等..",

    //医生选择
    title_doctor:"医生选择",
    address_doctor:"地址",
    tele_doctor:"电话",
    click_for_more_doctor:"点击查看更多",
    category_doctor:"科目",
    date_doctor:"日期",
    comments_doctor:"条评论",
    waiting_doctor:"正在为您搜索医生，请稍等..",

    //clinic info
    title_clinicinfo:"诊所信息",
    brief_clinicinfo:"诊所简介",
    type_clinicinfo:"科目类型",
    languages_clinicinfo:"服务语言",
    on_clinicinfo:"服务类型",
    onsite_clinicinfo:"实地问诊",
    online_clinicinfo:"远程问诊",
    charge_clinicinfo:"收费方式",
    support_clinicinfo:"支持",
    not_support_clniicinfo:"不支持",
    choose_doctor_clinicinfo:"预约医生",
    //doctor info:
    title_doctorinfo:"医生信息",
    about_doctorinfo:"医生简介",
    languages_doctorinfo:"服务语言",
    experience_doctorinfo:"行医经验",
    save_doctorInfo:"已保存到收藏栏",
    //mandarin:"Mandarin",
    //catonese:"Cantonese",
    //english:"",
    year:"年",
    not_fiiled:"未填写",
    doctor_type_doctorinfo:"科目类型",
    online_method_doctorinfo:"远程方式",
    open_hour_doctorinfo:"服务时间",
    make_appointment_doctorinfo:"选择时间",
    notime_doctorinfo:"该医生还没有提供服务时间的信息。",
    slot_doctorinfo:"预约时间",
    no_slot_doctorinfo:"抱歉,这天还没有可选择的时间段哦。",
    type_text_doctorinfo:"您是希望远程问诊还是去诊所实地问诊呢？",
    no_past_allowed:"无法选择过去的时间段。",

    //telepay
    title_medicare:"医保信息",
    question_medicare:"患者是否拥有Medicare卡?",
    yes_medicare:"患者有Medicare卡",
    no_medicare:"患者没有Medicare卡",
    confirm_medicare:"信息核对",
    tick_info_medicare:"我确认我有完整并正确的填写信息。",
    first_name:"持卡人名",
    first_name_pd:"请输入名",
    last_name:"持卡人姓",
    last_name_pd:"请输入姓",
    DOB:"出生日期",
    gender:"性别",
    medicare_number:"医保卡号",
    medicare_number_pd:"请输入10位Medicare号码",
    serial_number:"序列号",
    serial_number_pd:"请输入您的序列号",
    expire_date:"到期日期",
    expire_date_pd:"请选择到期日期",
    mobile:"手机号码",
    mobile_pd:"请输入患者手机号码",
    email:"电子邮箱",
    email_pd:"请输入患者电子邮箱",
    male:"男性",
    female:"女性",
    confirm:"确定预约",
    name:"患者姓名",
    doctor:"就诊医生",
    medicare_notice1:"拥有Medicare卡用户在支持bulk billing",
    medicare_notice2:"的诊所问诊可以全额报销。",
    medicare_notice3:"所有医保卡信息(比如姓名，出生日期等) ",
    medicare_notice4:"仅用于医保卡的验证。",
    medicare_notice5:"若未持有Medicare卡，就真费用需要自费。",

    //telesuccess
    success_title:"预约成功",
    success_notice1:"订单详情已发送至手机，请注意查收。",
    success_notice2:"",
    confirm_success:"完成",

    //account info page
    account_info:"个人信息",
    title_account_info:"基本信息",
    address:"地址",
    address_pd:"请输入地址",
    postcode:"邮编",
    postcode_pd:"请输入邮编",
    state:"州",
    state_pd:"请输入州",
    confirm_account:"确认更新",

    //MEDICARE INFO
    medicare_info:"医保信息",
    card_info:"医保卡信息",

    //medical history
    medical_history:"病史信息",
    chronic:"慢性病史",
    chronic_pd:"请输入慢性病史",
    allergy:"过敏史",
    allergy_pd:"请输入过敏史",
    medication_history:"用药历史",
    medication_history_pd:"请输入用药历史",
    family_history:"家族病史",
    family_history_pd:"请输入家族病史",
    
    //prescription
    e_prescription:"电子处方",
    overview:"处方总览",
    P_ID:"处方号",
    loading_pres:"正在搜索您的电子处方，请稍等...",
    no_pres:"您还没有电子处方，快去我的服务预约吧:)",
    //health record
    health_record:"电子病历",
    loading_record:"正在搜索您的电子病历，请稍等...",
    number:"号码",//号码
    patient_info:"病人信息",
    patient_statement:"病情陈述",
    description:"病人描述",
    files:"附件上传",
    doctor_diagnosis:"病人主诉",
    medical_advice:"诊疗意见",
    prescription:"处方信息",

    medicine_name:"药名",
    usage:"用法",
    dosage:"用量",
    repetition:"疗程",
    number_medicine:"数量",
    repeat:"是否重复",
    yes:"是",
    no:"否",
    no_record:"您还没有电子病历，去我的服务预约吧！",
    //online consultation
    online_title:"在线问诊",
    online_text1:"在本模块,Aicare小助手将收集您的相关资料，根据病情的初步评估来为您推荐匹配度最高的医生。",
    online_text2:"请仔细描述您的病情,如症状，患病时长，用药状况等。(*必填）",
    online_text3:"请按+号按钮来上传病症照片。(*必填)",
    attachment:"附件上传",
    online_text4:"如填写完毕，请点击提交进行上传。",
    submit:"提交",
    online_alert1:"您需要填写病情描述与上传附件。如无症状照片，您可以上传一张自拍:)",
    online_loading:"正在匹配医生..",
    upload_image_title:"照片上传",
    upload_image_text:"您可以上传与病情相关的照片，请问您是要打开相机拍照还是在相册进行选择?",
    open_camera:"打开相机",
    open_album:"在相册选择",
    cancel:"取消",

    //matching doctors
    matching_doctors_title:"匹配医生",
    scroll_down_more:"下滑浏览所有推荐医生",
    no_matching:"抱歉，目前找不到匹配的医生。",

    //alerts
    log_out_alert:"您确定要退出吗?",
    updating_module:"模块正在升级..将在下版本推出。",
    pw_update_success:"密码重设成功!",
    verification_code_wrong:"验证码错误",
    same_password:"两次密码需要一致",
    fill_name:"请输入名字",
    fill_mobile:"请输入电话",
    fill_password:"请输入密码",
    password_length:"密码需要至少六位数字",
    fill_code:"请输入验证码",
    read_TOS:"请阅读并同意用户须知",
    press_send:"请点击发送验证码",
    Today:"今日",
    login_notice:"游客模式",
    login_notice_text:"您好，您还处于游客模式，让我们来一键注册登陆吧。",
    go_login:"注册/登陆",
    vaccine_notice:"疫苗提醒",
    saved:"已保存",
    fill_serial:"请输入序列号",
    fill_medicare:"请输入十位医保卡号码",
    redirecting_pay:"正在前往支付页面..",
    vaccine_text:"基于来自health.gov.au官网的消息, 澳洲目前正在为1a和1b阶段人群接种疫苗，并已开始为2a阶段人群接种疫苗，所有年满50岁的成年人将首先开始接种。辉瑞疫苗将在所有阶段优先用于50岁以下的人群，阿斯利康疫苗将优先用于年满50岁的人群。在您进行新冠疫苗预约前，请提前确认是否满足当前接种要求，详情请移步官网了解更多。",
    trail_now:"开始体验",
    lans:["语言","中文","英语","粤语","法语","德语","俄语"],

}
