export default {
  orginfo: 'Personal Information',
  members: 'Members Management',
  resetPassword:'Reset Password',
  settings:'My Setting',
  logout:'Log Out',
  provider:'Get Start!',
  consumer:'I am Consumer',
  account:'Account',
  password:'Password',
  forgotPassword:'Forgot Password',
  signup:'Sign Up',
  login:'Login',
  name:'Name',
  mobile:'Mobile',
  email:'Email',
  verifyCode:'Verify code',
  confirm:'Confirmation',
  loginEmail:'Email login',
  loginMobile:'Mobile login',
  sendCode:'Send Code',
  resend:'Resend Code',
  binding:'Binding method',
  changePassword:'Change Password',
  mySetting:'My Settings',
  members:'Manage Members',
  introduction:'Introduction',
  mintro:'Member Introduction',
  mlan:'Member Languages',
  languages:'Languages',
  serviceType:'Service Type',
  stores:'Other Stores',
  uploadMember:'Add a Member',
  doctorInfo:'Member Detail',
}
