export default {
  orginfo: 'Personal Information',
  members: 'Members Management',
  resetPassword:'Reset Password',
  settings:'My Setting',
  logout:'Log Out',
  provider:'Get Start!',
  consumer:'I am Consumer',
  account:'Account',
  password:'Password',
  forgotPassword:'Forgot Password?',
  signup:'Sign Up',
  login:'Login',
  name:'name',
  mobile:'mobile',
  email:'email',
  verifyCode:'verify code',
  confirm:'confirmation',
}
