
export default {
    //Ts:["推荐医生","全科","牙科","心理","中医","儿科","康复","疫苗"],
    types:["Recommend","GP","Dentistry","Psychology","Chinese Medicine","Paediatrics","Physiotherapy","Vaccine"],

    //sign up 
    signup_success:"Sign Up Successfully!",
    name_up:"Name",
    name_up_pd:"Please Enter your real name",
    mobile_up:"Mobile",
    password_up:"Pawssword",
    ps_up_pd:"Please enter a 6 digits at least password",
    confirmation_up:"Confirmation",
    confirmation_up_pd:"Please enter the password again.",
    verification:"Verification",
    verification_pd:"Please enter the verification code.",
    send:"send",
    read:"I have read and accept the",
    TOS:"Term of Service.",
    code_send:"Verification code has been sent to your mobile.",

    //forget
    new_password:"New Password",
    new_ps_pd:"Please enter a new password. At least 6 digits.",

    //登陆页面
    phone_signin:"Mobile Number",
    phone_signin_placeholder:"Enter your mobile number",
    password_signin:"Account Password",
    password_signin_placeholder:"Enter your password",
    forget_password_signin:"Forget Password?",
    signup_signin:"Sign Up",
    signin:"Login In",
    guest_mode:"Browse as a guest",
    m_pd:"Phone Number",

    //首页
    myservice_homepage:"My Service",
    myappointment_homepage:"Latest Appointment",
    aitext_homepage:"Let AI assistant know how's your day.",
    ordertype_homepage:"You have booked a ",
    no_appointment1:"Hi, you don't have any appointment right now.",
    no_appointment2:"Let's go to My Service :)",

    //tabs
    homepage_tab:"Home",
    service_tab:"Covid Test",
    appointment_tab:"Appointment",
    account_tab:"Account",

    //服务页
    allservice_service:"Services",

    //预约页
    order_order:"Appointments",
    onsite_order:"On-site",
    online_order:"Online - ",
    cancel_order:"Cancel",
    change_order:"Update",
    contact_order:"Contact",
    notice_order:"Cancellations and updates can only be made at least one hour before the appointment.",
    cancelalert_order:"Do you want to cancel this appointment？It is only allowed at least 1 hour before the appointmnet.",
    confirm_cancel:"Confirm",
    cancel_success:"Appointment is cancelled",
    changealert_order:"Do you want to update your session？It is only allowed at least 1 hour before the appointment.",
    confirm_change:"Update Session",
    changealert2_order:"Do you want to update your session to ",
    changealert3_order:"？",
    change_success:"Appointment session has been updated.",
    no_order:"You do not have any appointment yet. Let's go to My Service.",
    fail:"Request failed. Recheck your network connection or call the customer service for assistance.",

    //账户页
    personalinfo_account:"Personal Info     ",
    medicare_info_account:"Medicare Info     ",
    medical_history_account:"Medical History   ",
    electronic_prescription_account:"E-prescription    ",
    medication_history_account:"Medication History",
    vaccine_record_account:"Vaccine Record    ",
    cure_history_account:"治愈历史",
    pathology_account:"Pathology Record  ",
    contact_us_account:"Contact Us:)      ",
    logout_account:"Log Out           ",
    signup_account:"Let's sign up.",
    confirm_logout:"Confirm",
    language_switch:"Language Setting",
    chi:"Chinese",
    eng:"English",
    lan_text:"Which language you prefer?",

    //need to add alerts translation here

    //种类页
    title_type:"Booking",
    category_type:"Categories",
    recommendation_type:"Good Doctors",
    all_type:"All",
    gp:"General Practice",
    children:"Paediatrics",
    mental:"Psychology",
    chinese:"Chinese Medicine",
    recovery:"Physiotherapy",
    dentist:"Dentistry",

    //诊所选择
    title_clinic:"Clinic Select",
    category_clinic:"Categories",
    date_clinic:"Date",
    comments_clinic:" comment",
    unknown_clinic:"unknown ",
    waiting_clinic:"We are searching for matching clinics. We appreciate your patience..",

    //医生选择
    title_doctor:"Doctor Select",
    address_doctor:"Address",
    tele_doctor:"Tele",
    click_for_more_doctor:"Click for more",
    category_doctor:"Categories",
    date_doctor:"Date",
    comments_doctor:" comment",
    waiting_doctor:"We are searching for matching doctors. We appreciate your patience..",

    //clinic info
    title_clinicinfo:"Clinic Info",
    brief_clinicinfo:"About",
    type_clinicinfo:"Categories",
    languages_clinicinfo:"Languages",
    on_clinicinfo:"Consultation Type",
    onsite_clinicinfo:"On-site Consultation",
    online_clinicinfo:"Online Consultation",
    charge_clinicinfo:"Billing",
    support_clinicinfo:"Support ",
    not_support_clniicinfo:"Not support ",
    choose_doctor_clinicinfo:"Choose a Doctor",
    //doctor info:
    title_doctorinfo:"Doctor Info",
    about_doctorinfo:"About",
    languages_doctorinfo:"Languages",
    experience_doctorinfo:"Experience",
    save_doctorInfo:"Saved to savelist.",
    //mandarin:"Mandarin",
    //catonese:"Cantonese",
    //english:"",
    year:" year",
    not_fiiled:"Unfilled",
    doctor_type_doctorinfo:"Categories",
    online_method_doctorinfo:"Remote Options",
    open_hour_doctorinfo:"Opening Hour",
    make_appointment_doctorinfo:"Select Session",
    notime_doctorinfo:"This doctor has not provided any info on working hour yet.",
    slot_doctorinfo:"Sessions",
    no_slot_doctorinfo:"Sorry, no seesions available on the selected date.",
    type_text_doctorinfo:"Choose booking way you like.",
    no_past_allowed:"You can not choose sessions in the past.",

    //telepay
    title_medicare:"Medicare Info",
    question_medicare:"Do you have Medicare Card?",
    yes_medicare:"Yes I do.",
    no_medicare:"No, I don't.",
    confirm_medicare:"Info Confirm",
    tick_info_medicare:"I have filled the form carefully.",
    first_name:"First Name",
    first_name_pd:"Please enter your first name",
    last_name:"Last Name",
    last_name_pd:"Please enter your last name",
    DOB:"Date of birth",
    gender:"Gender",
    medicare_number:"Medicare Number",
    medicare_number_pd:"Enter your 10 digit medicare number",
    serial_number:"Serial Number",
    serial_number_pd:"Enter your serial number",
    expire_date:"Expiry date",
    expire_date_pd:"Enter your expire date",
    mobile:"Mobile",
    mobile_pd:"Enter your mobile",
    email:"Email",
    email_pd:"Enter your email",
    male:"Male",
    female:"Female",
    confirm:"Confirm & Book",
    name:"Name",
    doctor:"Doctor",
    medicare_notice1:"Medicare covers consultation expense",
    medicare_notice2:"in clinics with bulk billing.",
    medicare_notice3:"All medicare infos(e.g. names, DOB) would ",
    medicare_notice4:"only be used for medicare card verification.",
    medicare_notice5:"You would need to pay the consulation fee.",

    //telesuccess
    success_title:"Book Successfully",
    success_notice1:"Booking details have been sent to your mobile/email.",
    success_notice2:"Please double check.",
    confirm_success:"Finish.",

    //account info page
    account_info:"Account_info",
    title_account_info:"Personal Info",
    address:"Address",
    address_pd:"Enter your address",
    postcode:"Postcode",
    postcode_pd:"Postcode",
    state:"State",
    state_pd:"Enter your state",
    confirm_account:"Update",

    //MEDICARE INFO
    medicare_info:"Medicare Info",
    card_info:"Card Info",

    //medical history
    medical_history:"Medical History",
    chronic:"Chronic",
    chronic_pd:"Please enter your chronics if any",
    allergy:"Allergy",
    allergy_pd:"Please enter your allergies if any",
    medication_history:"Medication History",
    medication_history_pd:"Please enter your medication history if any",
    family_history:"Family Medical History",
    family_history_pd:"Please enter your family medical history if any",
    
    //prescription
    e_prescription:"E-Prescription",
    overview:"Overview",
    P_ID:"P-ID",
    loading_pres:"We are searching for your E-prescriptions. We appreciate your paitence.",
    no_pres:"You have no prescriptions so far. Let's go to My Service:)",
    //health record
    health_record:"E-Record",
    loading_record:"We are searching for your E-health record. We appreciate your patience.",
    number:" number",//号码
    patient_info:"Patient Information",
    patient_statement:"Patient Statement",
    description:"Description",
    files:"Files",
    doctor_diagnosis:"Doctor Diagnosis",
    medical_advice:"Medical Advice",
    prescription:"Prescription info",
    no_record:"You don't have any E-record so far. Let's go to My Service.",

    medicine_name:"Medicine name",
    usage:"Usage",
    dosage:"Dosage",
    repetition:"Repetition",
    number_medicine:"Number",
    repeat:"Repeat or not",
    yes:"Yes",
    no:"No",

    //online consultation
    online_title:"Telehealth",
    online_text1:"Telehealth will collect your basic information and recommend you appropriate doctors for online consultation :)",
    online_text2:"Please describe your symptoms, illness duration, medication status and etc, within 100 words.",
    online_text3:"Upload any attachments related to your symptoms here.",
    attachment:"Attachment",
    online_text4:"If all infos are provided, please press button below to submit.",
    submit:"Submit",
    online_alert1:"You need to filled in all info(Description and Attachment) before submit. If there is no photo needed, just take a selfie:)",
    online_loading:"Searching doctors for you..",
    upload_image_title:"Upload Image",
    upload_image_text:"You can upload any image related to the symptoms. Do you want to take a photo with camera or select an image from album?",
    open_camera:"Open camera",
    open_album:"Open album",
    cancel:"Cancel",

    //matching doctors
    matching_doctors_title:"Matching Doctors",
    scroll_down_more:"Scroll down to see all doctors",
    no_matching:"Sorry, we do not find any matching doctors at the moment.",

    //alerts
    log_out_alert:"Do you want to log out?",
    updating_module:"This function is currently updating. It would come out in the next release.",
    pw_update_success:"Password Reset Success!",
    verification_code_wrong:"Wrong code.",
    same_password:"Two passwords need to be the same.",
    fill_name:"You need to fill in a name.",
    fill_mobile:"You need to fill in a mobile.",
    fill_password:"You need to fill in a password,",
    password_length:"Your password needs to be at least 6 digits.",
    fill_code:"You need to fill in verification code.",
    read_TOS:"You need to read and agree with Term of Service.",
    press_send:"Please press 'send' to get a verification code",
    Today:"Today",
    login_notice:"Guest Mode",
    login_notice_text:"Hi there, you are still a guest~ Let's sign up in 10 seconds!",
    go_login:"Sign up/Sign in",
    vaccine_notice:"vaccine_notice",
    saved:"Saved.",
    fill_serial:"Please fill in the serial number.",
    fill_medicare:"Please fill in a 10-digits medicare number",
    redirecting_pay:"Redirecting to payment page..",
    vaccine_text:"Based on official information form health.gov.au, we are delivering COVID-19 vaccination to people during phase 1a and 1b, and starting it for phase 2a currently. For those under the age of 50, Pfizer is prioritised at all stages. AstraZeneca will be administered to adults over the age of 50 initially. Please confirm that you satisfy the immunisation requirements before your visit.",
    trail_now:"Start Trial",
    lans:["language","Chinese","English","Cantonese","French","German","Russian"]
}   