import React from 'react';
import { StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  store:{
    marginTop:17,
    height:40,
    width:40,
  },
  img2:{
    marginTop:30,
    height:100,
    width:100,
  },
  img3:{
    height:50,
    width:70,
    marginLeft:78,
  },
  img4:{
    height:100,
    width:276,
  },
  buttonContainer:{
    width: 90,
    height: 90,
    marginTop:15,
    marginBottom:15,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: '#9ADAD6',
    borderRadius: 15,
    textAlign: 'center',
    justifyContent: "center",
    alignItems: "center" ,
  },
  buttonContainer2:{
    width: 90,
    height: 90,
    marginTop:15,
    marginBottom:15,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: '#196F75',
    borderRadius: 15,
    textAlign: 'center',
    justifyContent: "center",
    alignItems: "center" ,
  },
  buttonContainer3:{
    width: 90,
    height: 90,
    marginTop:15,
    marginBottom:15,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: '#FF816B',
    borderRadius: 15,
    textAlign: 'center',
    justifyContent: "center",
    alignItems: "center" ,
  },
  buttons:{
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: "center",
  },
  buttonContainer4:{
    width: 280,
    height: 100,
    borderRadius: 10,
    backgroundColor: "#98D8D4",
    alignItems: 'center',
    margin: 20,
  },
  buttonContainer5:{
    width: 280,
    height: 100,
    borderRadius: 10,
    backgroundColor: "#196F75",
    alignItems: 'center',
    margin: 20,
  },
  buttonContainer6:{
    width: 280,
    height: 100,
    borderRadius: 10,
    backgroundColor: "#FF816B",
    alignItems: 'center',
    margin: 20,
  },
  searchBar: {
    width: 315,
    height: 35,
    marginTop:15,
    marginBottom:30,
  },
  home: {
    width: 315,
    height: 140,
    backgroundColor: '#ffffff',
    borderRadius: 15,
  },
  card: {
    width: 315,
    height: 160,
    marginTop:15,
    marginBottom:15,
    backgroundColor: '#ffffff',
    borderRadius: 15,
    borderWidth: 1,
  },
  card2: {
    width: 330,
    height: 176,
    marginTop:15,
    marginBottom:15,
    backgroundColor: '#ffffff',
    borderRadius: 15,
    borderWidth: 1,
  },
  card3: {
    width: 316,
    height: 133,
    marginTop:15,
    marginLeft: 24,
    backgroundColor: '#f7fafa',
    borderRadius: 15,
  },
  cardHolder: {
    width: 340,
    height: 175,
  },
  mainImg:{
    height:120,
    width:120,
  },
  orderImg: {
    width: 375,
    height: 100,
  },
  plans: {
    width: 330,
    height: 120,
  },
  personIcon:{
    width: 78,
    height: 78,
  },
  iconImg:{
    width: 45,
    height: 40,
  },
  smallIconImg:{
    width: 20,
    height: 20,
    marginLeft:10,
    marginRight:10,
  },
  accountBar:{
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom:15,
  },
  profileBar:{
    width: 332,
    height: 25,
    marginTop: 15,
    marginBottom: 15,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  benefit: {
    width: 320,
    height: 60,
    marginTop:25,
    marginBottom:30,
    backgroundColor:'#68b0ab',
    borderRadius: 15,
    textAlign: 'center',
    justifyContent: "center",
    alignItems: "center" ,
  },
  orderButton: {
    width: 75,
    height: 30,
    backgroundColor: '#FF7E67',
    borderRadius: 10,
    textAlign: 'center',
    marginRight: 25,
    marginTop: 15,
    justifyContent: "center",
    alignItems: "center" ,
  },
  orderButton2: {
    width: 75,
    height: 30,
    backgroundColor: '#68B0AB',
    borderRadius: 10,
    textAlign: 'center',
    marginRight: 25,
    marginTop: 15,
    justifyContent: "center",
    alignItems: "center" ,
  },
  orderButton3: {
    width: 56,
    height: 25,
    backgroundColor: '#68B0AB',
    borderRadius: 10,
    marginRight: 25,
    marginLeft: 43,
    marginTop: 15,
    justifyContent: "center",
    alignItems: "center" ,
  },
  resumeImg: {
    width:110,
    height:110,
  },
  resumeInput: {
    width: 300,
    height: 22,
  },
  resumeInput1: {
    width: 115,
    height: 22,
  },
  resumeInput2: {
    width: 335,
    height: 22,
  },
  resumeButton: {
    width: 280,
    height: 40,
    marginTop: 40,
    backgroundColor: '#68B0AB',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: "center",
  },
  resumeSmallButton: {
    width: 60,
    height: 30,
    borderRadius: 10,
  },
  resumeTag: {
    backgroundColor: '#DDDDDD',
    width: 'auto',
    height: 30,
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 5,
    marginRight: 5,
    textAlign: 'center',
    paddingLeft:15,
    paddingRight:15,
  },
  resumeTag2: {
    backgroundColor: '#DDDDDD',
    width: 'auto',
    height: 30,
    paddingLeft:15,
    paddingRight:15,
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 5,
    marginRight: 5,
    textAlign: 'center',
  },
  bigIconImg: {
    width: 90,
    height: 90,
  },
  commentContainer1: {
    width: 130,
    height: 70,
    marginLeft: 25,
    marginRight: 25,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor:  '#68b0ab',
    borderRadius: 15,
  },
  commentContainer2: {
    width: 130,
    height: 70,
    marginLeft: 25,
    marginRight: 25,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor:  '#FF7E67',
    borderRadius: 15,
  },
  commentIcon: {
    width: 15,
    height: 15,
  },
  commentPerson: {
    width:40,
    height:40,
  },
  commentCard:{
    width: 345,
    height: 100,
  },
  commentTag: {
    width: 'auto',
    height: 30,
    textAlign: 'center',
    borderWidth: 1,
    borderRadius: 10,
    marginLeft:10,
    marginRight:10,
    paddingLeft:10,
    paddingRight:10,
  },
  incomeCard: {
    width:325,
    height: 60,
  },
  incomeIcon: {
    width: 40,
    height: 40,
  },
  finishImg: {
    width: 300,
    height: 225,
  },
  smallAddImg: {
    width: 25,
    height:25,
  },
  pendingImg: {
    width: 40,
    height:40,
  },
  timePicker: {
    width: 60,
    height: 30,
    borderWidth: 1,
    borderRadius: 10,
    marginLeft:20,
    marginRight:20,
    justifyContent: "center",
    alignItems: "center",
  },
  codeTab: {
    backgroundColor: '#68B0AB',
    width:'auto',
    marginTop: 3,
    marginLeft: 25,
    paddingLeft:10,
    paddingRight:10,
    paddingTop:5,
    paddingBottom:4,
    height:30,
    borderRadius:10,
  }
});
